// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKSLF6XsZmuYZDbZO-6bBZOCr1l12CJ3E',
    appId: '1:91794545956:web:6194f944146643c76167b1',
    messagingSenderId: '91794545956',
    projectId: 'flutter-chat-app-e9a69',
    authDomain: 'flutter-chat-app-e9a69.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e9a69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHzAlsmlk7ej12l7AQ3QOKqc3YzzxaCec',
    appId: '1:91794545956:android:9b5bd9c15f67cb5e6167b1',
    messagingSenderId: '91794545956',
    projectId: 'flutter-chat-app-e9a69',
    storageBucket: 'flutter-chat-app-e9a69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD19fXBK4kbb0ume4Q1vSUdlcs4P9pQAus',
    appId: '1:91794545956:ios:ce5a1539eec0d7f66167b1',
    messagingSenderId: '91794545956',
    projectId: 'flutter-chat-app-e9a69',
    storageBucket: 'flutter-chat-app-e9a69.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD19fXBK4kbb0ume4Q1vSUdlcs4P9pQAus',
    appId: '1:91794545956:ios:ce5a1539eec0d7f66167b1',
    messagingSenderId: '91794545956',
    projectId: 'flutter-chat-app-e9a69',
    storageBucket: 'flutter-chat-app-e9a69.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKSLF6XsZmuYZDbZO-6bBZOCr1l12CJ3E',
    appId: '1:91794545956:web:802d27c58d368fed6167b1',
    messagingSenderId: '91794545956',
    projectId: 'flutter-chat-app-e9a69',
    authDomain: 'flutter-chat-app-e9a69.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e9a69.appspot.com',
  );

}